ATM_Software/Controllers/AdministrationController.cs
using ATM_Software.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ATM_Software.Controllers
{
    public class AdministrationController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;

        public AdministrationController(RoleManager<IdentityRole> roleManager)
        {
            this.roleManager = roleManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateRoles(CreateRoleVM createRoleVM)
        {
            if (ModelState.IsValid)
            {
                IdentityRole identityRole = new IdentityRole
                {
                    Name = createRoleVM.RoleName
                };

                // save the roles
                IdentityResult result = await roleManager.CreateAsync(identityRole);
                if (result.Succeeded) return RedirectToAction("Index", "Home");

                foreach(IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }

            return View();
        }
    }
}

ATM_Software/Controllers/CashTransferController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ATM_Software.Controllers
{
    public class CashTransferController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.Current = "Transfer";
            return View();
        }
    }
}

ATM_Software/Controllers/WithdrawCashController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ATM_Software.Controllers
{
    public class WithdrawCashController : Controller
    {
        [Authorize]
        public IActionResult Index()
        {
            ViewBag.Current = "Withdraw";
            return View();
        }
    }
}

ATM_Software/Views/Shared/_AdminNav.cshtml
<nav class="navbar navbar-dark admin-nav-bg">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">ATM</a>
    </div>
</nav>

ATM_Software/Views/Shared/_AdminSidenav.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@


<div class="d-flex flex-column justify-content-between flex-shrink-0 bg-light"
     id="sidenav">
    <ul class="nav nav-pills flex-column mb-auto">
        <li class="menu-item my-2">
            <a href="" class="nav-link mx-2" aria-current="page">
                Create new account
            </a>
        </li>
        <li class="my-2">
            <a href="" class="nav-link mx-2 link-dark">
                Delete existing account
            </a>
        </li>
        <li class="my-2">
            <a href="#" class="nav-link mx-2 link-dark">
                Update account information
            </a>
        </li>
        <li class="my-2">
            <a href="#" class="nav-link mx-2 link-dark">
                Search for account
            </a>
        </li>
        <li class="my-2">
            <a href="#" class="nav-link mx-2 link-dark">
                View reports
            </a>
        </li>
    </ul>
    <div>
        <hr />
        <div class="dropdown mx-2 p-2">
            <strong>Exit</strong>
        </div>
    </div>
    <div>
        &nbsp;
    </div>
</div>

ATM_Software/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <title>@ViewData["Title"] - ATM_Software</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
    <link href="~/css/sidebars.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />

    <!--My added files-->

    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="~/fonts/icomoon/style.css">

    <link rel="stylesheet" href="~/css/owl.carousel.min.css">

    <!-- Style -->
    <link rel="stylesheet" href="~/css/style.css">

</head>
<body>

    @RenderBody()

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!--My Added files-->

    <script src="~/js/popper.min.js"></script>
    <script src="~/js/main.js"></script>
    <script src="~/js/sidebars.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ATM_Software/Views/Shared/_UserSidenav.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ATM_Software.Database.CustomIdentityUser> SignInManager

<div class="d-flex flex-column justify-content-between flex-shrink-0 bg-light"
     id="sidenav">
    <ul class="nav nav-pills flex-column mb-auto">
        <li class="@(ViewBag.Current == "Withdraw" ? " menu-item " : "") my-2">
            <a asp-controller="WithdrawCash"
               asp-action="Index"
               class="nav-link mx-2 @(ViewBag.Current == "Withdraw" ? " " : "link-dark")"
               aria-current="page">
                Withdraw Cash
            </a>
        </li>
        <li class="@(ViewBag.Current == "Transfer" ? " menu-item " : "") my-2">
            <a asp-controller="CashTransfer"
               asp-action="Index"
               class="nav-link mx-2 @(ViewBag.Current == "Transfer" ? " " : "link-dark")">
                Cash Transfer
            </a>
        </li>
        <li class="my-2">
            <a href="#" class="nav-link mx-2 link-dark">
                Deposit Cash
            </a>
        </li>
        <li class="my-2">
            <a href="#" class="nav-link mx-2 link-dark">
                Display Balance
            </a>
        </li>
    </ul>
    <div>
        <hr />
        @if (SignInManager.IsSignedIn(User))
        {
            <div class="dropdown mx-2 p-2">
                <button asp-controller="Account" asp-action="LogOut">
                    <strong>Exit</strong>
                </button>
            </div>
        }
        <div>&nbsp;</div>
    </div>
</div>

ATM_Software/Views/Shared/_Usernav.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ATM_Software.Database.CustomIdentityUser> SignInManager

<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white box-shadow">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ATM_Software</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Home" asp-action="Index">Home</a>
                    </li>

                    @if (!SignInManager.IsSignedIn(User))
                    {

                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                    }
                    else
                    {

                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="WithdrawCash" asp-action="Index">Cash</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Administration" asp-action="Index">Create Role</a>
                        </li>
                    }

                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Account" asp-action="AdminLogin">Admin</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
</header>